import { StyleSheet } from 'react-native';

const COLORS = {
    background: '#111111',
    cardBg: '#121212',
    primary: '#FFD900',
    white: '#FFFFFF',
    gray: '#9CA3AF',
    border: '#2A2A2A',
    activeBg: '#BEF264',
    activeText: '#166534',
    consumedBg: '#475569',
    consumedText: '#E2E8F0',
    withdrawnBg: '#ff000041',
    withdrawnText: '#ff0000',
    expiredBg: '#374151',
    expiredText: '#9CA3AF',
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    title: {
        fontSize: 20,
        fontWeight: 500,
        color: COLORS.white,
        fontFamily: 'InterDisplayMedium',
    },
    notifDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        width: 10,
        height: 10,
        borderRadius: 4,
        backgroundColor: '#FF3D00',
        borderWidth: 1,
    },
    tabsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 10,
        paddingVertical: 7,
        marginBottom: 16,
        marginTop: 8,
        justifyContent: 'space-between',
        backgroundColor: '#1E1E1E',
        marginLeft: 21,
        marginRight: 21,
        borderRadius: 10,
    },
    tab: {
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 24,
        backgroundColor: 'transparent',
    },
    activeTab: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
        borderRadius: 10,
    },
    tabText: {
        fontSize: 14,
        fontWeight: 500,
        color: COLORS.white,
        fontFamily: 'InterDisplayMedium',
        marginLeft: 20,
        marginRight: 20,
    },
    activeTabText: {
        color: '#1F2937',
        fontWeight: 900,
        fontFamily: 'InterDisplayMedium',
        marginLeft: 20,
        marginRight: 20,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 100,
    },
    availabilityCard: {
        backgroundColor: '#1E1E1E',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    cardHeader: {
        flexDirection: 'row',
        gap: 12,
        alignItems: 'center',
    },
    iconCircle: {
        bottom: 14,
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.gray,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardInfo: {
        flex: 1,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    availabilityTitle: {
        fontSize: 20,
        fontWeight: 500,
        color: COLORS.white,
        fontFamily: 'InterDisplayMedium',
        flex: 1,
        textTransform: 'capitalize',
    },
    scheduleText: {
        fontSize: 12,
        fontWeight: 400,
        color: COLORS.white,
        fontFamily: 'InterDisplayRegular',
        marginBottom: 8,
        textTransform: 'capitalize',
    },
    bottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    offersText: {
        fontSize: 12,
        fontWeight: 400,
        color: COLORS.white,
        fontFamily: 'InterDisplayRegular',
        textTransform: 'capitalize',
    },
    postedTime: {
        fontSize: 12,
        fontWeight: 400,
        color: COLORS.white,
        fontFamily: 'InterDisplayRegular',
        textTransform: 'capitalize',
    },
    statusActive: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 24,
        backgroundColor: COLORS.activeBg,
    },
    statusConsumed: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 24,
        backgroundColor: COLORS.consumedBg,
        borderWidth: 1,
        borderColor: '#ffffff77',
    },
    statusWithdrawn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 24,
        backgroundColor: COLORS.withdrawnBg,
    },
    statusExpired: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 24,
        backgroundColor: COLORS.expiredBg,
    },
    statusText: {
        fontSize: 10,
        fontWeight: 900,
        fontFamily: 'InterDisplaySemiBold',
        lineHeight: 12,
        textTransform: 'capitalize',
    },
    statusTextActive: {
        color: COLORS.activeText,
    },
    statusTextConsumed: {
        color: COLORS.consumedText,
    },
    statusTextWithdrawn: {
        color: COLORS.withdrawnText,
    },
    statusTextExpired: {
        color: COLORS.expiredText,
    },
    addButton: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        backgroundColor: COLORS.primary,
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 24,
    },
    addButtonText: {
        fontSize: 16,
        fontWeight: 700,
        color: '#1F2937',
        fontFamily: 'InterDisplay-Bold',
    },
});

export default styles;