import { StyleSheet } from 'react-native';
const COLORS = {
  background: '#111111',
  white: '#FFFFFF',
  cardBg: '#161616',
  yellow: '#fcd303',
  textMain: '#ffffff',
  textSecondary: '#a1a1a1',
  tagBg: '#121212',
  inputBg: '#222222',
};
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background, paddingBottom: 40 },
  scrollContent: { padding: 20, paddingBottom: 60 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 500,
    color: COLORS.white,
    fontFamily: 'InterDisplayMedium',
  },
  notifDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 4,
    backgroundColor: '#FF3D00',
    borderWidth: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1D1D1D',
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 24,
    height: 48,
    borderWidth: 1,
    borderColor: 'rgba(249, 250, 251, 0.10)',
  },
  input: {
    flex: 1,
    color: '#9CA3AF',
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 15,
    alignItems: 'center',
  },
  sectionTitle: { color: COLORS.yellow, fontSize: 18, fontWeight: 'bold' },
  seeAllText: { color: COLORS.textSecondary, fontSize: 12 },

  // Recommended Card Styling
  recCard: {
    marginHorizontal: 16,
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    marginBottom: 20,
    overflow: 'hidden',
  },
  cardImage: { height: 180, padding: 15, justifyContent: 'space-between' },
  badgeContainer: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.yellow,
  },
  badgeText: { color: COLORS.yellow, fontSize: 11, fontWeight: 'bold' },
  heartIcon: {
    position: 'absolute',
    top: 15,
    right: 15,
    color: '#fff',
    fontSize: 22,
  },
  profileRow: { flexDirection: 'row', alignItems: 'center' },
  avatarCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.yellow,
    marginRight: 12,
  },
  avatarInitial: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  profileName: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  verifiedText: { color: COLORS.textSecondary, fontSize: 12 },

  cardInfo: { padding: 16 },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  roleTitle: { color: '#fff', fontSize: 22, fontWeight: 'bold' },
  rateText: { color: COLORS.yellow, fontSize: 22, fontWeight: 'bold' },
  perHr: { fontSize: 12 },
  locationText: {
    color: COLORS.yellow,
    opacity: 0.8,
    fontSize: 14,
    marginTop: 4,
  },

  availabilityBox: {
    backgroundColor: COLORS.inputBg,
    padding: 12,
    borderRadius: 12,
    marginVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  clockIcon: { fontSize: 18, marginRight: 10 },
  availLabel: { color: COLORS.textSecondary, fontSize: 12 },
  availValue: { color: '#fff', fontSize: 15, fontWeight: '600' },
  availSub: { color: COLORS.textSecondary, fontSize: 12 },

  tagRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 15 },
  tag: {
    backgroundColor: COLORS.tagBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  tagText: { color: '#fff', fontSize: 13 },

  viewProfileBtn: {
    backgroundColor: COLORS.yellow,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewProfileText: { color: '#000', fontWeight: 'bold', fontSize: 16 },

  // Gig Item Styling
  gigCard: {
    marginHorizontal: 16,
    backgroundColor: COLORS.cardBg,
    padding: 16,
    borderRadius: 16,
    marginTop: 15,
  },
  row: { flexDirection: 'row' },
  gigAvatar: { width: 48, height: 48, borderRadius: 24 },
  gigTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  bookmarkIcon: { fontSize: 18 },
  priceChip: {
    backgroundColor: COLORS.inputBg,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.yellow,
  },
  priceChipText: { color: COLORS.yellow, fontSize: 13, fontWeight: 'bold' },
  gigTime: { color: COLORS.textSecondary, fontSize: 12 },
  spotsText: {
    color: COLORS.yellow,
    fontSize: 12,
    textAlign: 'right',
    fontWeight: '600',
    marginTop: 5,
  },
});

export default styles;
