import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
    paddingBottom: 60,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 15,
    marginBottom: 24,
  },
  notifDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 4,
    backgroundColor: '#FF3D00',
    borderWidth: 1,
  },
  input: {
    flex: 1,
    color: '#9CA3AF',
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    paddingHorizontal: 12,
  },

  filterScroll: {
    alignItems: 'center',
    height: 90,
    marginBottom: 10,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    marginRight: 12,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    gap: 8,
  },
  filterBtnActive: {
    backgroundColor: '#FFD900',
  },
  filterBtnText: {
    color: '#FFF',
    marginRight: 5,
  },
  filterBtnTextActive: {
    color: '#000',
    fontWeight: '600',
    marginRight: 5,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: 20,
  },
  countText: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 20,
  },
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortText: {
    color: '#FFD900',
    fontSize: 14,
    marginRight: 4,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 20,
  },
  listContent: {
    paddingBottom: 20,
  },
  card: {
    backgroundColor: '#111',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#374151',
  },
  candidateImage: {
    width: '100%',
    height: 120,
    objectFit: 'cover',
    position: 'relative',
  },
  statusBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusYellow: {
    backgroundColor: '#FFD900',
  },
  statusDark: {
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 50,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 16,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: '23%',
    left: 10,
  },
  avatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#555',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#FFF',
  },
  candidateName: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    lineHeight: 20,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    color: '#FFF',
    fontSize: 12,
    marginLeft: 4,
  },
  cardContent: {
    padding: 15,
  },
  tagContainer: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  tag: {
    backgroundColor: '#1E1E1E',
    paddingHorizontal: 20,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 400,
    lineHeight: 16,
  },
  availabilityRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  availabilityTitle: {
    color: '#FFF',
    fontSize: 14,
    marginLeft: 12,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  availabilityDates: {
    color: '#fff',
    fontSize: 12,
    marginTop: 2,
    marginLeft: 12,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  engageButton: {
    backgroundColor: '#FFD900',
    height: 40,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  engageButtonText: {
    color: '#1F2937',
    fontSize: 16,
    marginRight: 8,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  lockButton: {
    backgroundColor: '#374151',
    height: 40,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  lockButtonText: {
    color: '#FFF',
    fontSize: 16,
    marginLeft: 8,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
});
