import { StyleSheet } from 'react-native';
const COLORS = {
  background: '#111111',
  cardBg: '#121212',
  primary: '#FFD900',
  secondaryText: '#9E9E9E',
  border: '#333333',
  green: '#84CC16',
  white: '#FFFFFF',
  disabled: '#7C7D7E',
};
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background, paddingBottom: 40 },
  scrollContent: { padding: 20, paddingBottom: 60 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1D1D1D',
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 24,
    height: 48,
    borderWidth: 1,
    borderColor: 'rgba(249, 250, 251, 0.10)',
    marginHorizontal: 20,
  },
  input: {
    flex: 1,
    color: '#9CA3AF',
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  title: {
    fontSize: 24,
    fontWeight: 500,
    color: COLORS.white,
    fontFamily: 'InterDisplayMedium',
  },
  notifDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 4,
    backgroundColor: '#FF3D00',
    borderWidth: 1,
  },
  filterRow: { flexDirection: 'row', marginBottom: 24 },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 32,
    backgroundColor: '#121212',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  activeChip: { backgroundColor: COLORS.primary },
  chipText: { color: COLORS.white, fontWeight: '600' },
  activeChipText: {
    color: '#111827',
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
    fontSize: 14,
  },
  resultsText: {
    color: COLORS.white,
    fontSize: 14,
    marginBottom: 24,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  card: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 27,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(245, 245, 245, 0.07)',
  },
  cardTopRow: { flexDirection: 'row', justifyContent: 'space-between' },
  profileInfo: { flexDirection: 'row' },
  avatar: { width: 40, height: 40, borderRadius: 27.5 },
  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: -6,
    backgroundColor: COLORS.green,
    borderRadius: 100,
    padding: 2,
    borderWidth: 2,
    borderColor: COLORS.cardBg,
  },
  nameSection: { marginLeft: 12 },
  workerName: {
    color: 'white',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  roleBadge: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 2,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  workerRoleWrapper: {
    display: 'flex',
    flexDirection: 'row',
  },
  roleText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: 400,
    fontFamily: 'InterDisplayRegular',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    gap: 2,
  },
  ratingVal: {
    color: COLORS.primary,
    marginRight: 2,
    fontSize: 12,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  reviewCount: {
    color: COLORS.white,
    fontSize: 12,
    marginLeft: 2,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  priceSection: { alignItems: 'flex-end' },
  priceText: {
    color: COLORS.primary,
    fontSize: 20,
    fontWeight: 600,
    fontFamily: 'InterDisplaySemiBold',
  },
  hrText: {
    fontSize: 12,
    fontWeight: 400,
    fontFamily: 'InterDisplayRegular',
  },
  distanceText: {
    color: COLORS.white,
    fontSize: 12,
    marginTop: 4,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  bioText: {
    color: '#F9FAFB',
    fontSize: 14,
    marginVertical: 12,
    lineHeight: 20,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 16 },
  tag: {
    backgroundColor: '#1E1E1E',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  tagText: {
    color: COLORS.white,
    fontSize: 12,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  line: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(247, 254, 231, 0.08)',
    marginBottom: 16,
  },
  actionRow: { flexDirection: 'row', justifyContent: 'space-between' },
  outlineBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    paddingVertical: 12,
  },
  outlineBtnText: {
    color: COLORS.primary,
    fontWeight: 400,
    fontSize: 12,
    fontFamily: 'InterDisplayRegular',
  },
  filledBtn: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 16,
  },
  filledBtnText: {
    color: '#1F2937',
    fontWeight: 500,
    fontSize: 12,
    fontFamily: 'InterDisplayMedium',
  },
  disabledBtn: {
    flex: 1,
    paddingVertical: 9,
    backgroundColor: COLORS.disabled,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  disabledBtnText: { color: '#111827', fontWeight: 500 },
  busyTag: {
    backgroundColor: '#333',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    marginTop: 8,
  },
  busyText: { color: COLORS.secondaryText, fontSize: 12 },

  premiumBanner: {
    backgroundColor: '#050505',
    borderRadius: 20,
    padding: 12,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#1a1a1a',
  },
  premiumIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 100,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: 'rgba(252, 211, 77, 0.16)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  premiumTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 600,
    marginBottom: 16,
    fontFamily: 'InterDisplaySemiBold',
  },
  premiumSub: {
    color: COLORS.secondaryText,
    textAlign: 'center',
    fontWeight: 400,
    fontSize: 12,
    fontFamily: 'InterDisplayRegular',
    lineHeight: 20,
    marginBottom: 16,
    maxWidth: 235,
  },
  premiumBtn: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 40,
    paddingVertical: 12,
    borderRadius: 10,
  },
});
export default styles;
