import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  restoreText: {
    fontSize: 16,
    color: '#FFD900',
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  titleSection: {
    marginTop: 48,
    marginBottom: 30,
  },
  mainTitle: {
    textAlign: 'center',
    color: '#FFFFFF',
    marginBottom: 12,
    fontSize: 26,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  subtitle: {
    fontSize: 15,
    color: '#A0A0A0',
    textAlign: 'center',
    lineHeight: 20,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#383119',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: 40,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  toggleButtonActive: {
    backgroundColor: '#181711',
  },
  toggleText: {
    fontSize: 14,
    color: '#BAB59C',
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  saveBadge: {
    backgroundColor: '#FFD900',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 8,
  },
  saveBadgeText: {
    fontSize: 12,
    color: '#000000',
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  planCard: {
    backgroundColor: '#1E1E1E',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 30,
    marginBottom: 20,
  },
  premiumCard: {
    backgroundColor: '#1E1E1E',
    borderRadius: 24,
    padding: 30,
    borderWidth: 1,
    borderColor: '#FFD900',
    marginBottom: 20,
    position: 'relative',
  },
  popularBadge: {
    position: 'absolute',
    top: -12,
    alignSelf: 'center',
    backgroundColor: '#FFD900',
    paddingHorizontal: 25,
    paddingVertical: 6,
    borderRadius: 24,
  },
  popularBadgeText: {
    fontSize: 12,
    color: '#000000',
    lineHeight: 16,
    letterSpacing: 1.1,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  planName: {
    fontSize: 19,
    color: '#A0A0A0',
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
    marginBottom: 8,
  },
  premiumName: {
    fontSize: 16,
    color: '#FFD700',
    marginBottom: 12,
    marginTop: 8,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 20,
  },
  priceAmount: {
    fontSize: 48,
    color: '#FFFFFF',
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  priceUnit: {
    fontSize: 18,
    color: '#A0A0A0',
    marginBottom: 8,
    marginLeft: 4,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  featuresList: {
    marginBottom: 24,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 6,
  },
  crossIcon: {
    fontSize: 16,
    color: '#666666',
    marginRight: 12,
    fontWeight: 'bold',
  },
  featureText: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.90)',
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  featureTextDisabled: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.30)',
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  standardButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  standardButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  premiumButton: {
    backgroundColor: '#FFD700',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  premiumButtonText: {
    fontSize: 16,
    color: '#000000',
    fontWeight: 'bold',
  },
  disclaimer: {
    fontSize: 12,
    color: '#A0A0A0',
    textAlign: 'center',
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
    marginTop: 10,
  },
  disclaimerLink: {
    color: '#A0A0A0',
    textDecorationLine: 'underline',
  },
});

export default styles;
