import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  headerTitle: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 10,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  giftIconContainer: {
    alignItems: 'center',
    marginVertical: 30,
  },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: 40,
    backgroundColor: '#181711',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#374151',
  },
  heroSection: {
    alignItems: 'center',
    marginBottom: 25,
  },
  title: {
    color: 'white',
    fontSize: 24,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
    lineHeight: 30,
    marginBottom: 4,
  },
  subtitle: {
    color: '#fff',
    textAlign: 'center',
    lineHeight: 16,
    paddingHorizontal: 20,
    marginBottom: 16,
    fontWeight: 400,
    fontFamily: 'InterDisplayMedium',
    maxWidth: 280,
  },
  infoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#262216',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 24,
    borderWidth: 0.5,
    borderColor: '#4B5563',
  },
  infoText: {
    color: '#FBBF24',
    fontSize: 12,
    marginLeft: 6,
    fontWeight: 400,
    fontFamily: 'InterDisplayMedium',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  statCard: {
    flex: 0.48,
    backgroundColor: '#000',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: '#FDE68A',
  },
  statCardActive: {
    borderColor: '#FDE68A',
  },
  statNumber: {
    color: 'white',
    fontSize: 32,
    fontFamily: 'InterDisplayBold',
    fontWeight: 700,
  },
  statLabel: {
    color: 'white',
    fontSize: 14,
    marginTop: 4,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  sectionLabel: {
    color: 'white',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
    marginBottom: 20,
  },
  codeContainer: {
    backgroundColor: '#1D1D1D',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 0.5,
    borderColor: 'rgba(249, 250, 251, 0.10)',
  },
  codeText: {
    color: '#9CA3AF',
    fontSize: 20,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  shareButton: {
    backgroundColor: '#FFD900',
    borderRadius: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
  },
  shareButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
    marginLeft: 12,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#FFF',
    marginHorizontal: 20,
  },
  dividerText: {
    color: 'white',
    marginHorizontal: 15,
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  emailInputWrapper: {
    marginBottom: 32,
  },
  emailInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141414',
    borderRadius: 12,
    paddingLeft: 15,
    paddingRight: 6,
    height: 56,
    borderWidth: 0.5,
    borderColor: '#FBBF24',
  },
  textInput: {
    flex: 1,
    color: 'white',
    fontSize: 14,
  },
  sendButton: {
    backgroundColor: 'white',
    paddingHorizontal: 24,
    height: 44,
    borderRadius: 10,
    justifyContent: 'center',
  },
  sendButtonText: {
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
    fontSize: 16,
    color: '#1F2937',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  recentBadge: {
    backgroundColor: 'white',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  recentBadgeText: {
    color: '#1F2937',
    fontSize: 12,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  referralItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 30,
  },
  referralInfo: {
    flex: 1,
    marginLeft: 15,
  },
  referralName: {
    color: 'white',
    fontSize: 16,
    marginBottom: 8,
    lineHeight: 22,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  referralSubtext: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderWidth: 1,
  },
  statusVerified: {
    borderColor: '#4B5563',
    backgroundColor: '#262216',
    borderWidth: 0.5,
  },
  statusPending: {
    borderColor: '#4B5563',
    borderWidth: 0.5,
    backgroundColor: '#374151',
  },
  statusText: {
    fontSize: 11,
    marginLeft: 5,
    color: '#FFFBEB',
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
});

export default styles;
