import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111', paddingHorizontal: 20 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  scrollContainer: { paddingBottom: 40 },
  card: {
    backgroundColor: '#1D1D1D',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginVertical: 8,
    flexDirection: 'row',
    marginTop: 20,
  },
  avatar: { width: 44, height: 44, borderRadius: 25, marginRight: 8 },
  labelSmall: {
    color: '#F5F5F5',
    fontSize: 12,
    opacity: 0.85,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  name: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 600,
    fontFamily: 'InterDisplayBold',
    lineHeight: 22,
    marginTop: 4,
    marginBottom: 8,
  },
  rowAlign: { flexDirection: 'row', alignItems: 'center' },
  rating: {
    color: '#FFCE31',
    marginRight: 4,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  shiftCard: {
    flexDirection: 'column',
  },
  shiftWrapper: {
    flexDirection: 'row',
    marginTop: 24,
    alignItems: 'center',
  },
  role: {
    color: '#fff',
    opacity: 0.6,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  sectionTitle: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
    marginTop: 10,
    marginBottom: 20,
  },
  inputBox: {
    backgroundColor: '#1D1D1D',
    borderRadius: 12,
    paddingHorizontal: 19,
    paddingVertical: 14,
    marginBottom: 16,
    justifyContent: 'center',
    flex: 1,
  },
  inputText: {
    color: '#FFF',
    fontSize: 14,
    flex: 1,
    marginRight: 8,
    fontFamily: 'InterDisplayMedium',
    fontWeight: 500,
  },
  inputTexttime: {
    textAlign: 'center',
  },
  row: { flexDirection: 'row', gap: 16 },
  labelRate: {
    color: '#FFF',
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  rateInputContainer: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255, 217, 0, 0.35)',
    borderRadius: 12,
    justifyContent: 'center',
    paddingHorizontal: 19,
    paddingVertical: 11,
  },
  rateInput: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  mathText: { color: '#000', fontSize: 40, marginHorizontal: 15 },
  hoursText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  shiftPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 217, 0, 0.08)',
    marginVertical: 15,
  },
  totalLabel: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'InterDisplayMedium',
  },
  totalValue: {
    color: '#FFCE31',
    fontSize: 20,
    fontFamily: 'InterDisplayExtraBold',
    fontWeight: '900',
  },
  mapContainer: { borderRadius: 12, overflow: 'hidden', marginTop: 5 },
  locationLabelBox: {
    backgroundColor: '#1D1D1D',
    padding: 10,
    marginBottom: 20,
    borderRadius: 12,
    justifyContent: 'center',
  },
  buttonText: {
    textAlign: 'center',
  },
  mapFrame: { height: 150, width: '100%' },
  webview: { flex: 1, backgroundColor: '#1A1A1A' },
  contextInput: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  sendButton: {
    backgroundColor: '#FFD900',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    paddingVertical: 16,
  },
  sendButtonText: {
    color: '#102217',
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 10,
  },
});

export default styles;
