import { StyleSheet } from 'react-native';

const COLORS = {
  background: '#111111',
  cardBg: '#121212',
  primary: '#FFD900',
  white: '#FFFFFF',
  gray: '#9CA3AF',
  darkGray: '#6B7280',
  textDark: '#1F2937',
  border: '#2A2A2A',
  yellow: '#D4AF37',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: COLORS.white,
    fontFamily: 'InterDisplayBold',
    textAlign: 'center',
    lineHeight: 22.5,
  },
  notificationWrapper: {
    position: 'relative',
  },
  notifDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF3D00',
  },
  tabsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  tab: {
    height: 32,
    paddingHorizontal: 15,
    paddingVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.cardBg,
  },
  activeTab: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  tabText: {
    fontSize: 13,
    fontWeight: 500,
    color: COLORS.white,
    fontFamily: 'InterDisplayMedium',
    lineHeight: 16,
    textTransform: 'capitalize',
  },
  activeTabText: {
    color: COLORS.textDark,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  offerCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 217, 0, 0.1)',
  },
  jobTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: COLORS.white,
    fontFamily: 'InterDisplaySemiBold',
  },
  timeAgo: {
    fontSize: 15,
    fontWeight: 400,
    color: COLORS.gray,
    fontFamily: 'InterDisplayRegular',
  },
  infoPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  infoPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#1E1E1E',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  infoPillTextYellow: {
    fontSize: 12,
    fontWeight: 400,
    color: COLORS.primary,
    fontFamily: 'InterDisplayRegular',
  },
  infoPillText: {
    fontSize: 12,
    fontWeight: 400,
    color: COLORS.white,
    fontFamily: 'InterDisplayRegular',
  },
  description: {
    fontSize: 16,
    fontWeight: 400,
    color: COLORS.white,
    fontFamily: 'InterDisplayRegular',
    lineHeight: 20,
    marginBottom: 8,
  },
  showMore: {
    fontSize: 16,
    fontWeight: 500,
    color: COLORS.primary,
    fontFamily: 'InterDisplayMedium',
    marginBottom: 16,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  declineButton: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.yellow,
    backgroundColor: COLORS.cardBg,
  },
  declineButtonText: {
    fontSize: 14,
    fontWeight: 700,
    color: COLORS.primary,
    fontFamily: 'InterDisplaySemiBold',
    lineHeight: 16,
    textTransform: 'capitalize',
  },
  acceptButton: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  acceptButtonText: {
    fontSize: 14,
    fontWeight: 700,
    color: COLORS.textDark,
    fontFamily: 'InterDisplaySemiBold',
    lineHeight: 16,
    textTransform: 'capitalize',
  },
  bottomCTA: {
    marginTop: 32,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  ctaIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 20,
    backgroundColor: '#353535',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  ctaText: {
    fontSize: 20,
    fontWeight: 400,
    color: COLORS.gray,
    fontFamily: 'InterDisplayRegular',
    textAlign: 'center',
    lineHeight: 30,
    marginBottom: 10,
  },
});

export default styles;
