import { StyleSheet } from 'react-native';

const COLORS = {
  background: '#111111',
  cardBg: '#121212',
  primary: '#FFD900',
  white: '#FFFFFF',
  gray: '#9CA3AF',
  textSecondary: '#acacac',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: 500,
    color: COLORS.white,
    fontFamily: 'InterDisplayMedium',
    marginLeft: 50,
  },
  markAllRead: {
    fontSize: 14,
    fontWeight: 500,
    color: '#FBBF24',
    fontFamily: 'InterDisplayMedium',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1D1D1D',
    borderRadius: 8,
    paddingHorizontal: 12,
    marginHorizontal: 20,
    marginBottom: 24,
    height: 48,
    borderWidth: 1,
    borderColor: 'rgba(249, 250, 251, 0.10)',
  },
  input: {
    flex: 1,
    color: '#9CA3AF',
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'InterDisplayRegular',
    fontWeight: 400,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 900,
    color: COLORS.textSecondary,
    fontFamily: 'InterDisplaySemiBold',
    marginBottom: 16,
    marginTop: 8,
  },
  notificationCard: {
    flexDirection: 'row',
    backgroundColor: '#1E1E1E',
    borderRadius: 9,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(231, 249, 253, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginTop: 8,
  },
  iconContainerRed: {
    width: 28,
    height: 28,
    borderRadius: 24,
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  newDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
  },
  notificationContent: {
    flex: 1,
    marginLeft: 12,
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  notificationTitle: {
    fontSize: 16,
    fontWeight: 900,
    color: COLORS.white,
    fontFamily: 'InterDisplaySemiBold',
    flex: 1,
    marginRight: 8,
  },
  notificationTime: {
    fontSize: 12,
    fontWeight: 400,
    color: COLORS.gray,
    fontFamily: 'InterDisplayRegular',
  },
  notificationDescription: {
    fontSize: 14,
    fontWeight: 400,
    color: COLORS.gray,
    fontFamily: 'InterDisplayRegular',
    lineHeight: 20,
  },
  noResults: {
    fontSize: 16,
    fontWeight: 400,
    color: COLORS.gray,
    fontFamily: 'InterDisplayRegular',
    textAlign: 'center',
    marginTop: 40,
  },
});

export default styles;
